spring.profiles.active=sit
#spring.profiles.active=prod

#DMT Transaction History Table:
#Request Status - 
#91=Unknown cases
#0=Pending 
#1=Success
#2=Credited
#3=Rejected
#4=Refund processed
#6=Failure
#-1=Unknown

#Status - 
#0=Success
#1=Failed
#2=Initiated (Hold)
#3=Refund Pending
#4=Refunded
#5=Under Process
#6=Partially Success
#7=Requested
#8=Pending
#9=Pending
#10=rejected
#11=Refund processed